### ISSUE TITLE
Không thể comment entry của mình

### ISSUE THREAD

**Issue by xuanduc987** [QuangTranXuan/blog_system#1]
Không thể comment ở entry của mình, chỉ có thể comment ở entry của người mình đã follow thôi

**Comment by QuangTranXuan** [comment]
Commit trước có vẻ đúng rồi, chỉ cần người login thì comment được, không cần phải follow user mới comment được :v Đề bài cũng không rõ ràng lắm. Thôi thì sửa theo ý chuyên gia vậy :v

**Comment by QuangTranXuan** [comment]
Vì lúc sửa theo ý kiến trước nên xảy ra xung đột :v

**Comment by QuangTranXuan** [comment]
Comment bây giờ chỉ cho phép: Người đã logged-in comment trên entry của mình hoặc entry của người mà mình follow. Người đã logged-in và unlogged-in chỉ có thể xem entry và comments tương ứng của mọi người khác (Theo ý kiến chủ quan một Website thực tế nên để người đã logged-in comment trên mọi entry vì khi đã logged-in là đã có định danh rồi).

**Comment by xuanduc987** [comment]
Chả hiểu vừa nói cái gì :)))

- can make a comment on a entry (of owner and followed user) (display comment, name and date)
Trích requirement :))

**Comment by QuangTranXuan** [comment]
Thì rõ ràng là requirement thõa mãn rồi đúng không? Còn comment được trên entry của người không follow được hay không thì requirement không nói, nhưng nghĩ là nên có :v

**Comment by xuanduc987** [comment]
Có đoạn
Everyone (including no sign-in user)
- can read all posts and their comments (with pagination)
- cannot make a comment

Vậy là không follow thì không comment được mà

**Comment by QuangTranXuan** [comment]
:v Thôi thì thế cũng được, mình đọc thì mình hiểu là unlogged-in user mới "cannot make a comment" chứ logged-in rồi thì việc gì phải chặn comment, có chặn thì chặn follow hoặc "read entry", chứ được đọc entry mà không cho comment khi đã có định danh rồi thì chắc FB cũng chưa làm :v

**Comment by QuangTranXuan** [comment]
Suy nghĩ từ thực tế nó thế :v

**Comment by xuanduc987** [comment]
:)) chả biết thế nào
